name: Build Project
on:
  push:
    branches:
      - main
      - 'release/**'
      - 'feature/**'
  pull_request_target:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

       # Tests
      - name: Unit tests
        run: yarn test:cov
      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          fail_ci_if_error: true